import { useCallback,useEffect,useMemo,useRef,useState } from "react";import type { ArcadeSettings,GameEngine,GameId,GameSnapshot,Screen } from "../../arcade/types";import { GAME_META } from "../../arcade/types";import { ArcadeAudio } from "../../arcade/audio";import { defaults,loadPlayer,loadScores,loadSettings,saveScore,saveSettings } from "../../arcade/storage";import { PixelButton } from "./PixelButton";import { ArcadeDecor } from "./ArcadeDecor";import { GameCanvas } from "./GameCanvas";
const ids=Object.keys(GAME_META) as GameId[];
export function ArcadeApp(){const [screen,setScreen]=useState<Screen>("home"),[game,setGame]=useState<GameId>("pinball"),[selected,setSelected]=useState(0),[settings,setSettings]=useState<ArcadeSettings>(defaults),[hydrated,setHydrated]=useState(false),[paused,setPaused]=useState(false),[snapshot,setSnapshot]=useState<GameSnapshot>({score:0}),[finalScore,setFinalScore]=useState<number|null>(null),[initials,setInitials]=useState("AAA"),[scores,setScores]=useState(()=>({pinball:[],galaga:[],pacman:[],tetris:[]} as ReturnType<typeof loadScores>)),[scoreTab,setScoreTab]=useState<GameId>("pinball"),[settingsReturn,setSettingsReturn]=useState<Screen>("home"),[run,setRun]=useState(0);const engineRef=useRef<GameEngine|null>(null);const audio=useMemo(()=>new ArcadeAudio(settings),[]);
 useEffect(()=>{setSettings(loadSettings());setScores(loadScores());setInitials(loadPlayer());setHydrated(true)},[]);useEffect(()=>{if(!hydrated)return;saveSettings(settings);audio.setSettings(settings)},[settings,hydrated,audio]);
 const sound=(n:Parameters<ArcadeAudio["play"]>[0])=>audio.play(n);const go=(s:Screen)=>{sound("select");setScreen(s)};const launch=(id:GameId)=>{setGame(id);setSnapshot({score:0});setFinalScore(null);setPaused(false);setRun(v=>v+1);go("game")};const over=useCallback((v:number)=>{sound("over");setFinalScore(v)},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.code==="KeyM"){setSettings(v=>({...v,muted:!v.muted}));return}if(e.code==="KeyP"&&screen==="game"&&!finalScore){setPaused(v=>!v);return}if(e.code==="Escape"){if(finalScore){setFinalScore(null);setScreen("select")}else if(paused)setPaused(false);else if(screen!=="home")setScreen(screen==="game"?"select":"home")}if(screen==="select"){if(e.code==="ArrowLeft")setSelected(v=>(v+3)%4);if(e.code==="ArrowRight")setSelected(v=>(v+1)%4);if(e.code==="Enter")launch(ids[selected])}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[screen,selected,paused,finalScore]);
 const save=()=>{if(finalScore===null)return;setScores(saveScore(game,initials,finalScore));sound("high");setScoreTab(game);setFinalScore(null);setScreen("scores")};
 const content=()=>{if(screen==="home")return <Home onPlay={()=>go("select")} onScores={()=>go("scores")} onSettings={()=>{setSettingsReturn("home");go("settings")}} onCoin={()=>{audio.startMusic();sound("coin")}}/>;if(screen==="select")return <Select selected={selected} setSelected={setSelected} launch={launch}/>;if(screen==="scores")return <Scores scores={scores} tab={scoreTab} setTab={setScoreTab} back={()=>go("home")}/>;if(screen==="settings")return <Settings value={settings} setValue={setSettings} back={()=>go(settingsReturn)} controls={()=>go("controls")}/>;if(screen==="controls")return <Controls back={()=>go("settings")}/>;return <Game game={game} snapshot={snapshot} setSnapshot={setSnapshot} paused={paused} setPaused={setPaused} finalScore={finalScore} initials={initials} setInitials={setInitials} save={save} skip={()=>{setFinalScore(null);setScreen("select")}} restart={()=>{setFinalScore(null);setPaused(false);setRun(v=>v+1)}} settings={()=>{setPaused(false);setSettingsReturn("game");go("settings")}} exit={()=>{setFinalScore(null);setPaused(false);go("select")}} sound={sound} engineRef={engineRef} over={over} run={run}/>};
 return <main className={`pixel-arcade ${settings.crt?"crt-on":""}`} onPointerDown={()=>audio.unlock()}><div className="screen-shell"><header><span className="brand-small">PIXEL ARCADE</span><span className="status">CREDITS 03&nbsp;&nbsp; {settings.muted?"MUTED":"SOUND ON"}</span></header>{content()}<div className="scanlines"/></div></main>}
function Home({onPlay,onScores,onSettings,onCoin}:{onPlay:()=>void;onScores:()=>void;onSettings:()=>void;onCoin:()=>void}){return <section className="home-screen"><ArcadeDecor/><div className="home-menu"><div className="logo"><span>PIXEL</span><strong>ARCADE</strong></div><button className="insert" onClick={onCoin}>INSERT COIN ◉</button><PixelButton autoFocus onClick={onPlay}>▶ PLAY</PixelButton><PixelButton onClick={onScores}>★ HIGH SCORES</PixelButton><PixelButton onClick={onSettings}>⚙ SETTINGS</PixelButton><PixelButton onClick={()=>document.documentElement.requestFullscreen?.()}>⛶ FULLSCREEN</PixelButton></div></section>}
function Cabinet({id,active,onClick}:{id:GameId;active:boolean;onClick:()=>void}){const m=GAME_META[id];return <button className={`cabinet accent-${m.accent} ${active?"selected":""}`} onClick={onClick}><span className="selector">▼</span><h2>{m.title}</h2><div className={`cabinet-screen preview-${id}`}><i/><i/><i/><i/></div><div className="cabinet-controls">● ● ◉</div><p>{m.subtitle}<br/><b>1 PLAYER</b></p></button>}
function Select({selected,setSelected,launch}:{selected:number;setSelected:(n:number)=>void;launch:(g:GameId)=>void}){return <section className="menu-screen select-screen"><h1>SELECT YOUR MACHINE</h1><div className="cabinet-grid">{ids.map((id,i)=><Cabinet key={id} id={id} active={i===selected} onClick={()=>{setSelected(i);launch(id)}}/>)}</div><p className="key-help">← → SELECT &nbsp; • &nbsp; ENTER PLAY &nbsp; • &nbsp; ESC BACK</p></section>}
function Scores({scores,tab,setTab,back}:{scores:ReturnType<typeof loadScores>;tab:GameId;setTab:(g:GameId)=>void;back:()=>void}){return <section className="menu-screen panel-screen"><h1>HIGH SCORES</h1><div className="tabs">{ids.map(id=><PixelButton key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{GAME_META[id].title}</PixelButton>)}</div><ol className="leaderboard">{scores[tab].map((s,i)=><li key={`${s.initials}-${i}`}><b>{String(i+1).padStart(2,"0")}</b><span>{s.initials}</span><strong>{String(s.score).padStart(6,"0")}</strong></li>)}</ol><PixelButton onClick={back}>← BACK</PixelButton></section>}
function Settings({value,setValue,back,controls}:{value:ArcadeSettings;setValue:(v:ArcadeSettings)=>void;back:()=>void;controls:()=>void}){const row=(label:keyof ArcadeSettings)=><div className="setting-row"><span>{label.toUpperCase()}</span>{typeof value[label]==="number"?<input aria-label={label} type="range" min="0" max="100" value={value[label] as number} onChange={e=>setValue({...value,[label]:+e.target.value})}/>:<PixelButton onClick={()=>setValue({...value,[label]:!value[label]})}>{value[label]?"ON":"OFF"}</PixelButton>}</div>;return <section className="menu-screen panel-screen"><h1>SETTINGS</h1><div className="settings-box">{row("music")}{row("sfx")}{row("crt")}<div className="setting-row"><span>FULLSCREEN</span><PixelButton onClick={()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen()}>TOGGLE</PixelButton></div></div><div className="row"><PixelButton onClick={controls}>CONTROLS</PixelButton><PixelButton onClick={back}>← BACK</PixelButton></div></section>}
function Controls({back}:{back:()=>void}){return <section className="menu-screen panel-screen"><h1>CONTROLS</h1><div className="controls-list">{ids.map(id=><article key={id}><h2>{GAME_META[id].title}</h2>{GAME_META[id].controls.map(c=><p key={c}>{c}</p>)}</article>)}</div><p>P PAUSE &nbsp; M MUTE &nbsp; ESC BACK</p><PixelButton onClick={back}>← BACK</PixelButton></section>}
